# Generated by Django 4.1.7 on 2023-09-23 18:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gardener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Sin procesar'), ('P', 'Procesada'), ('T', 'Terminada')], default='S', max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message="El teléfono debe tener en el siguiente formato: '+999999999'. Hasta 15 caracteres.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(max_length=255, null=True)),
                ('scheduled_to', models.DateField(null=True)),
                ('scheduled_at', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gardener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jardineria.gardener')),
            ],
        ),
    ]
