# Generated by Django 4.1.7 on 2023-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jardineria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
